# Disable blank issues to enforce structured reporting
blank_issues_enabled: false

contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/Md-Moklesar-Rahman-Bappy/anime/discussions
    about: >
      Ask questions, share ideas, and discuss topics with the community.

  - name: 📖 Documentation & Guides
    url: https://github.com/Md-Moklesar-Rahman-Bappy/anime/wiki
    about: >
      Read the official documentation, tutorials, and reference guides.

  - name: 🙋 Support / Help
    url: https://github.com/Md-Moklesar-Rahman-Bappy/anime/issues
    about: >
      If you're unsure whether it's a bug or feature request,
      open an issue and we will guide you.
